// -*- C++ -*-
// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================
#ifndef AIDA_Dev_IDEVFITTER_H
#define AIDA_Dev_IDEVFITTER_H 1

#include "AIDA/IFitter.h"

namespace AIDA {
namespace Dev {

/** 
 * @interface IDevFitter
 *
 * Developer interface for AIDA::IFitter
 *
 * All the setters defined at user level.
 *
 * @author Jakub Moscicki, Max Turri, Victor Serbo
 * @author Andreas Pfeiffer, Max Sang, Tony Johnson, Lorenzo Moneta
 *
 * @stereotype developer
 */

class IDevFitter : virtual public AIDA::IFitter {

public: 
    /// Destructor.
    virtual ~IDevFitter() { /* nop */; }

  /**
   * Constants specifying the type of fit.
   *
   */
    enum { BINNED_FIT = 0, UNBINNED_FIT = 1 };
}; // class
} // namespace Dev
} // namespace AIDA
#endif /* ifndef AIDA_Dev_IDEVFITTER_H */
