//
//    Copyright 2007 Andreas Pfeiffer
//
/*
 *  This file is part of iAIDA.
 *
 *  iAIDA is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as 
 *  published by the Free Software Foundation, either version 3 of 
 *  the License.
 *
 *  iAIDA is distributed in the hope that it will be useful, but 
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public 
 *  License along with iAIDA.  If not, see <http://www.gnu.org/licenses/>.
 */

// -*- C++ -*-
// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================
#ifndef AIDA_Dev_IDEVFITPARAMETERSETTINGS_H
#define AIDA_Dev_IDEVFITPARAMETERSETTINGS_H 1

#include "AIDA/IFitParameterSettings.h"

namespace AIDA {
namespace Dev {

/**
 * @interface IDevFitParameterSettings
 *
 * Developer interface for AIDA::IFitParameterSettings.
 *
 * This class is empty since all the setters are defined in user interface.
 *
 * @author Jakub Moscicki, Max Turri, Victor Serbo
 * @author Andreas Pfeiffer, Max Sang, Tony Johnson, Lorenzo Moneta
 *
 * @stereotype developer
 */
class IDevFitParameterSettings : virtual public AIDA::IFitParameterSettings {

public: 
    /// Destructor.
    virtual ~IDevFitParameterSettings() { /* nop */; }
}; // class
} // namespace Dev
} // namespace AIDA
#endif /* ifndef AIDA_Dev_IDEVFITPARAMETERSETTINGS_H */
