// -*- C++ -*-
// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================
#ifndef AIDA_Dev_IDEVFITPARAMETERSETTINGS_H
#define AIDA_Dev_IDEVFITPARAMETERSETTINGS_H 1

#include "AIDA/IFitParameterSettings.h"

namespace AIDA {
namespace Dev {

/**
 * @interface IDevFitParameterSettings
 *
 * Developer interface for AIDA::IFitParameterSettings.
 *
 * This class is empty since all the setters are defined in user interface.
 *
 * @author Jakub Moscicki, Max Turri, Victor Serbo
 * @author Andreas Pfeiffer, Max Sang, Tony Johnson, Lorenzo Moneta
 *
 * @stereotype developer
 */
class IDevFitParameterSettings : virtual public AIDA::IFitParameterSettings {

public: 
    /// Destructor.
    virtual ~IDevFitParameterSettings() { /* nop */; }
}; // class
} // namespace Dev
} // namespace AIDA
#endif /* ifndef AIDA_Dev_IDEVFITPARAMETERSETTINGS_H */
