// -*- C++ -*-
// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================
#ifndef AIDA_ICONSTANTS_H
#define AIDA_ICONSTANTS_H 1

//  This file is part of the AIDA library
//  Copyright (C) 2002 by the AIDA team.  All rights reserved.
//  This library is free software and under the terms of the
//  GNU Library General Public License described in the LGPL.txt 

#define AIDA_VERSION "3.2.1"
#define AIDA_VERSION_MAJOR 3
#define AIDA_VERSION_MINOR 2
#endif /* ifndef AIDA_ICONSTANTS_H */
